name: Build and deploy a headlight infant school React + vite project

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup node js
    - name: Setup Node.js
      uses: actions/setup-node@v4

      with:
        node-version: 20

    # Install dependecies
    - name: Install dependecies
      run: npm install

    # Build project
    - name: Build project
      run: npm run build

    # Deploy to gh pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist

